default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || "postgresql://#{ENV.fetch('POSTGRES_USER','postgres')}:#{ENV.fetch('POSTGRES_PASSWORD','password')}@#{ENV.fetch('DB_HOST','db')}:#{ENV.fetch('DB_PORT','5432')}/#{ENV.fetch('POSTGRES_DB','potterdb_development')}" %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || "postgresql://#{ENV.fetch('POSTGRES_USER','postgres')}:#{ENV.fetch('POSTGRES_PASSWORD','password')}@#{ENV.fetch('DB_HOST','db')}:#{ENV.fetch('DB_PORT','5432')}/#{ENV.fetch('POSTGRES_DB','potterdb_test')}" %>

production:
  <<: *default
  # Prefer DATABASE_URL for production
  url: <%= ENV['DATABASE_URL'] || "postgresql://#{ENV.fetch('POSTGRES_USER')}:#{ENV.fetch('POSTGRES_PASSWORD')}@#{ENV.fetch('DB_HOST','db')}:#{ENV.fetch('DB_PORT','5432')}/#{ENV.fetch('POSTGRES_DB','potterdb_production')}" %>
